version: "2.1"
services:
    fabconnect_0:
        container_name: firefly_fabconnect_0
        image: ghcr.io/hyperledger/firefly-fabconnect:latest
        command: -f /fabconnect/fabconnect.yaml
        volumes:
            - fabconnect_receipts_0:/fabconnect/receipts
            - fabconnect_events_0:/fabconnect/events
            - ./runtime/blockchain/fabconnect.yaml:/fabconnect/fabconnect.yaml
            - ./runtime/blockchain/ccp_testnetwork.yaml:/fabconnect/ccp.yaml
            - $HOME/fabric-samples/test-network/organizations:/etc/firefly/organizations

         # If your services are listening on “localhost” and not on the Docker network (172.x.x.x),
         # you need to run your container on the host network (network_mode)
#        network_mode: host

         # In Mac to connect to the Docker host from inside a Docker container, use the "host.docker.internal" hostname
         # should work without additional configuration, but if not, you can set the extra host this way.
         # With "host-gateway" instead of an IP address.
#        extra_hosts:
#            - "host.docker.internal:host-gateway"
        ports:
            - "3000:3000"
        healthcheck:
            test:
                - CMD
                - wget
                - -O
                - '-'
                - http://localhost:3000/status
        logging:
            driver: json-file
            options:
                max-file: "1"
                max-size: 10m
volumes:
    fabconnect_events_0: {}
    fabconnect_receipts_0: {}